### ISSUE TITLE
Followup Department Feedback

### ISSUE THREAD

**Issue by laurenancona** [CityOfPhiladelphia/community-health-explorer#10]
- [x] We’d like to display all numbers to the tenth data point, across the board
- [x] Let’s remove the ‘date updated’ field from the chart visualization
- [x] Remove citywide numbers(display) from planning district dimension

---

_moving low sample sizes to separate issue_

---

How to connote out local vs. national data source for Philadelphia in the ‘Top 10 Cities’ dimension
- [x] Have the label for the Philadelphia local source look/read like: Philadelphia (local source)
  ~~~In the Sources notes add “Local source:” in front of the local source description (for example, “Local source: School District of Philadelphia, 2014”~~~ _moved to separate issue_

**Comment by MeaganLP** [comment]
- [ ] Remove citywide numbers(display) from planning district dimension
