### ISSUE TITLE
Update data field `description` for local sources

### ISSUE THREAD

**Issue by laurenancona** [CityOfPhiladelphia/community-health-explorer#11]
In the Sources notes add “Local source:” in front of the local source description (for example, “Local source: School District of Philadelphia, 2014”

**Comment by laurenancona** [comment]
If @MeaganLP or @AmoryH could knock this out in the data itself, I've updated the labels in charts.

**Comment by MeaganLP** [comment]
Sure thing @laurenancona - I will update the sources in the Top 10 group where 'Local source:' is appropriate.

**Comment by laurenancona** [comment]
Awesome, @MeaganLP. When you're finished, feel free to go ahead and close this issue. 

If you want to get fancy, you can add `closes #11` to your commit message in Prose, and it will auto close it here.

**Comment by laurenancona** [comment]
Bump @MeaganLP - do you think you'll have a moment to get to this this week?

**Comment by laurenancona** [comment]
pinging @AmoryH and @MeaganLP: are you satisfied with the state these are in, or is this still outstanding?

**Comment by laurenancona** [comment]
closed in https://github.com/CityOfPhiladelphia/community-health-explorer/commit/b8b772cf7ce428c23ad04aae3fe93a644ca94f66 by @MeaganLP
