### ISSUE TITLE
Filter Top-10-Cities charts to hide bar when no data present

### ISSUE THREAD

**Issue by laurenancona** [CityOfPhiladelphia/community-health-explorer#13]

**Comment by laurenancona** [comment]
This may not be possible for release

**Comment by AmoryH** [comment]
@MeaganLP and I are actually not sure what this is referring to. The over time charts are line charts....what bars?

**Comment by laurenancona** [comment]
@AmoryH my bad; this was meant to be Top-10

**Comment by laurenancona** [comment]
closing for now, revisit in future
