### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by Kistine** [CityOfPhiladelphia/community-health-explorer#22]
I'm doing a detailed comb-through to see if there's anything small/miscellaneous that we've missed to date, to help get this as polished as possible. 
### Planning District
- [x] @AmoryH - **On Planning District, is the text under 'Viral Load' accurate? It says "Percentage of persons diagnosed living with HIV, who were alive at year end and had a viral load ≤200 at most recent test. By default, persons without a viral load are classified as not being suppressed." I am quite possibly  misunderstanding because I didn't work with AACO as much, but wouldn't it be that, without a viral load, they're classified as BEING suppressed, rather than 'not being suppressed'?**  
- [x] On Planning District, for the Social capital card, revise the description to add a space between 'yes' and 'to,' add quotation marks around the question and a question mark at the end. The text would then read: Percentage of adults reporting "yes" to, "Have people in your neighborhood ever worked together to improve the neighborhood? For example, through a neighborhood watch, creating a community garden, building a community playground, or participating in a block party?"
- [x] On Planning District, for the Poor or fair health card, add quotation marks so it reads: Percentage of adults who rate their health as fair or poor in response to the question, "In general, would you say that your health is excellent, very good, good, fair, or poor?"
- [x] @AmoryH - On Planning District, under 'Adults covered by Medicaid, 18-64 years of age,' it says, "Percentage of adults 18-64 years reporting insurance coverage through Medicaid, Medical Assistance (M.A.), HealthChoices, or Access Card." I thought 'Medicaid' is just another term for 'Medical Assistance'? 
- [x] On Planning District, under 'Percentage of adults 18-64 years,' add comma and quotation marks, so that it reads: Percentage of adults 18-64 years answering "yes" to the question, "In the past year, has there been any time when you were sick or injured AND did not seek health care because of the cost?"
- [x] Adjust punc. on "Adults w/mental illness"
- [x] @laurenancona The Planning District page ends abruptly, with some of the last cards on built environment going off-screen. When on my laptop, my scroller also goes off-screen, and the only way to see the other cards is to use the down arrow. Can we easily add the white border at the end of the page, like we see on the others?
### Racial Disparity:
- [x] perhaps put real salary number as example for what '100% under FPL' would mean under 'Poverty' card?
- [x] Adjust punc. on Poor or Fair Health  
- [x] @AmoryH, the description for "Adults never tested for HIV, 18-39 years of age" needs fine-tuning - seems unfinished. 
- [x] fix 'Adults forgoing care due to cost, 18-64 years of age'
- [x] fix Adults with diagnosed mental health condition
- [x] fix typos in Access to recreational facilities
- [x] @AmoryH and @MeaganLP - I think the title 'Access to recreational facilities' should be changed to 'Use of recreational facilities.' My use of a nearby rec center is not an adequate proxy for how 'accessible' it is. Would you and your team be okay with that edit?
### Citywide over Time
- [x] **same question re: Viral suppression as noted in Planning Districts above**
- [x] fix Social capital typos
- [x] fix typos in Poor or fair health
- [x] add periods to HIV charts' descriptions.
- [x] fix typos in 'Adults never tested for HIV, 18-39 years of age'
- [x] fix typos in Low birth weight births
- [x] add 'age' to description for 'Children up to date on immunizations, 19-35 months of age'
- [x] fix 'Adults forgoing care due to cost, 18-64 years of age'
- [x] fix Adults with diagnosed mental health condition
- [x] fix typos in Access to recreational facilities
- [x] @AmoryH and @laurenancona. It seems like the chart 'Pedestrian and bicycle accidents per 100,000 children, <18 years of age' should go under 'Built Environment' with the chart on 'Pedestrian and bicycle accidents per 100,000.' Right now, it's under 'Child Health.' If this is something PDPH already decided on, then @AmoryH can just check this item off. 

**About page**
- [x] @laurenancona the link associated with the Office of Open Data and Digital Trans. links to OIT. Perhaps use one of the following links, or ask Tim.  
- https://alpha.phila.gov/departments/office-of-the-chief-administrative-officer/functions/office-of-open-data-and-digital-transformation/
- https://alpha.phila.gov/press-releases/mayor/mayor-elevates-innovation-efforts-with-creation-of-open-data-and-digital-transformation-office/

**Comment by laurenancona** [comment]
@Kistine (stop me if you've heard this one) Medicaid is actually a separate, state/federally-funded program to provide heath coverage if you have very low income, where Medicare does so for people 65+ or have a severe disability, regardless of income.

**Comment by Kistine** [comment]
thanks @laurenancona, this makes it clearer what that was supposed to mean. i know about medicare, just never heard it referred to as 'M.A.' before. When I was doing health advocacy, we only used M.A. as either a reference to Medicaid specifically, or as an umbrella term for any public assistance for health care access. From online searching, it looks like it's used inconsistently. Ah, jargon. I was going to suggest we say 'Medicare' instead of M.A., but I just looked up the Community Health Assessment and see that this is how it is written in there, and we should mirror that language, so I'll check off this  item. Thanks! :)

**Comment by laurenancona** [comment]
@Kistine gotcha, thank you.
Also: thanks for the fine detail review. 
It may be more pleasant for you, rather than typing out descriptions for things like punctuation, etc, (where there isn't a question about the data itself) to just hop into prose.io and edit it right in the data, since that's what @AmoryH or @MeaganLP will be doing anyway, and it'll save you all those keystrokes! The instructions are still in the wiki, but also happy to run through again in a bit.

**Comment by Kistine** [comment]
That would be nice! @AmoryH and @MeaganLP, you okay with that? just for typos. I'll check with you on any language change etc.

**Comment by AmoryH** [comment]
I think checking for typos is fine. I'm going to go in and do a bunch of text editing myself - just around the HHS questions so that the actual survey question is separated with a semicolon. So that will be a lot of descriptions.

**Comment by Kistine** [comment]
@laurenancona, fyi that Amory gave me the ok to make typos fixes so I will take care of any I list in this Issue.

**Comment by laurenancona** [comment]
@Kistine where are we with these? when you have a moment, would you update any remaining checks?

**Comment by Kistine** [comment]
just pushed commit changing title from 'Access of Recreation Centers' to 'Use of Recreation Centers' with ok from Amory/Meagan

**Comment by Kistine** [comment]
pushed commits that show income examples for FPL on the Poverty cards in all four dimensions

**Comment by Kistine** [comment]
@MeaganLP checked with AACO and revised the viral load language.
