### ISSUE TITLE
Firearm  homicides

### ISSUE THREAD

**Issue by AmoryH** [CityOfPhiladelphia/community-health-explorer#23]
For Over Time
1. The chart for Firearm homicide rate per 100,000, ≥20 years of age is missing. 
2. The data in the Firearm homicide rate per 100,000, <20 years of age chart is actually the ≥20 data even though it's correct in prose. 

For Racial Disparity
1. The chart for Firearm homicides, ≥ 20 years of age is missing.

**Comment by laurenancona** [comment]
Closed in 63fd80bdd6f166a35701627511c442cc65157ee1
