### ISSUE TITLE
Handling blanks/no data/low sample size

### ISSUE THREAD

**Issue by AmoryH** [CityOfPhiladelphia/community-health-explorer#28]
Hide cards in [planning districts](http://cityofphiladelphia.github.io/community-health-explorer/planning-districts/#tobacco-and-alcohol) when value of indicator is blank (because `0` is inaccurate).
<img width="273" alt="screen shot 2016-06-29 at 7 28 16 pm" src="https://cloud.githubusercontent.com/assets/2152151/16472108/a8f2fb5e-3e2f-11e6-89d6-755576ccf234.png">

**Comment by laurenancona** [comment]
@AmoryH this appears to be tied to whether or not there is a `0` value entered in the corresponding cell.

If blank, nothing appears. Either way is ok with me, perhaps you can determine internal preference, and make any required edits to the data? [See also](https://phl.slack.com/archives/G0GT7CYSF/p1466628279000034)

**Comment by AmoryH** [comment]
@laurenancona Would it be possible to eliminate cards for Planning Districts where there is no data?

**Comment by laurenancona** [comment]
@AmoryH  I will look into what that would entail.

**Comment by laurenancona** [comment]
This almost works in https://github.com/CityOfPhiladelphia/community-health-explorer/commit/67350fac56aaf0f73bd161cbd31be6481ebb8772:
[Test](http://cityofphiladelphia.github.io/community-health-explorer/planning-districts/#tobacco-and-alcohol) using `Central` indicator `Secondhand smoke exposure` (which is blank)
- correctly adds `.hidden` on initial load, per Liquid filter in [markup](https://github.com/CityOfPhiladelphia/community-health-explorer/blob/gh-pages/planning-districts.html#L48)
- [removes](https://github.com/CityOfPhiladelphia/community-health-explorer/blob/gh-pages/scripts/planning-districts.js#L94) `.hidden` when you click another district that has a value for that indicator

but when you reassign `Central` by click or dropdown, it fails to re-add the `.hidden` class

/cc @timwis

**Comment by Kistine** [comment]
Hurrah!!!
