### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by AmoryH** [CityOfPhiladelphia/community-health-explorer#32]
Limited Access to Healthy Foods description in Planning Districts page has a dead link and runs outside of the "tile."

**Comment by laurenancona** [comment]
@timwis: do you have a good idea for parsing links in the middle of a data field like that?

**Comment by timwis** [comment]
To wrap long words/URLs: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/
Alternatively, use `{{ description | markdownify }}` to allow descriptions to contain markdown links.

**Comment by laurenancona** [comment]
closed in 58680ac069bfbd062d579d7bb3bfab6a435bbc9e
