### ISSUE TITLE
X-axis 

### ISSUE THREAD

**Issue by AmoryH** [CityOfPhiladelphia/community-health-explorer#33]
Some of the x-axis numbers on the [Top Ten charts](http://cityofphiladelphia.github.io/community-health-explorer/top-10-cities/) are really strange and the last number at the far right on the axis will be cut off. Example: Violent crime rate.

**Comment by AmoryH** [comment]
Is also happening for [Racial Disparity](http://cityofphiladelphia.github.io/community-health-explorer/racial-disparity/) charts.

**Comment by laurenancona** [comment]
closed in cb30bca
