### ISSUE TITLE
Broken links on about page

### ISSUE THREAD

**Issue by MeaganLP** [CityOfPhiladelphia/community-health-explorer#40]
- [x] Links under “Data:” on bottom of the About page don’t work
- [x] Feedback link returns 'Network Error' page

**Comment by laurenancona** [comment]
I think I'd left these blank until we knew where we were going to publish the data (?)
I'll link them to the sets on ODP so we get the analytics from downloads there (even though the source of _those_ links is actually this repo ;)

**Comment by Kistine** [comment]
@laurenancona i like that idea! we have the odp entry queued up, but fyi that it's marked to private rn
