### ISSUE TITLE
Broken link in indicator text

### ISSUE THREAD

**Issue by MeaganLP** [CityOfPhiladelphia/community-health-explorer#41]
For Planning Districts and Citywide Overtime the Built Environment indicator, Access to Healthy Food description contains a link to the food access report that does not work.

**Comment by Kistine** [comment]
@laurenancona, I fixed this using markdown

**Comment by laurenancona** [comment]
@Kistine THAT'S AMAZING, lookit you!

**Comment by Kistine** [comment]
@laurenancona lol, thank you my techie guru!!
