### ISSUE TITLE
Planning District scroll and bottom border

### ISSUE THREAD

**Issue by Kistine** [CityOfPhiladelphia/community-health-explorer#42]
- [ ] is it possible to add a scroll bar on the right side as appears in the other dimensions?
- [ ] Is it easy to add back the bottom border? The 'Use of Rec Centers' card is cut off by the bottom of the page.

**Comment by MeaganLP** [comment]
It's be great if the bottom border issue could be resolved in time for Cheryl's review.

The other is less important to us, though functionally seems really useful.

**Comment by laurenancona** [comment]
This never had a border at bottom, but did have some extra padding that I think got trashed in some recent style updates. Will restore the padding.
