### ISSUE TITLE
Text populated based on low sample-size indicators

### ISSUE THREAD

**Issue by MeaganLP** [CityOfPhiladelphia/community-health-explorer#43]
Sample size 1, 2, and 3 codes:
- When 3: where sample size is low, so information is not displayed: 
- [ ] Please show this text: "Data missing for some race/ethnic subgroups due to small sample size." instead of the current, "Sample size inadequate: Asian";;;;;;;; 
- [ ] For Planning districts please show: "Data missing for some planning districts due to small sample size." 

**unless we do something different to solve this?
*Launch

**Comment by MeaganLP** [comment]
Can you tell me what self-serve means? Usually I would consider text changes something we should do in prose, but these particular texts were populated into the notes field through code, I thought.

**Comment by laurenancona** [comment]
@MeaganLP apologies, I meant to Slack you about that! That was a lo-fi, manual solution because there weren't that many of them. That text is just in the `chartComments` field, so  for anything like those, it would be awesome if you could take a shot at updating. Let me know if that's not what you're referring to, or I'm otherwise misunderstanding.

**Comment by laurenancona** [comment]
@MeaganLP @Kistine @AmoryH To be clear: you'd like these more generalized statements to replace the current versions that names the specific missing data?

**Comment by MeaganLP** [comment]
Depending on which situation you're talking about (between the 2 and 3 designation). Perhaps we should chat by phone @laurenancona quickly so that no unnecessary work gets done? I'm free after 4 today or in the morning.

**Comment by laurenancona** [comment]
@MeaganLP I'm in DC at a mapping event until EOD today, but can do a call tmrw?

So what I'm reading is for these changes are only for designation `3`?

**Comment by MeaganLP** [comment]
We had a correction for designation 3 that needs to change before launch and a small adjustment for designation 2 that can be considered an enhancement. 

Let's check in briefly tomorrow. Let me know what time works best for you - I'm free all day, but would prefer a call after 10:30 if that wouldn't cause a hold up.

**Comment by MeaganLP** [comment]
@laurenancona

**Comment by laurenancona** [comment]
I'm going to take a pass at this right now, with the provision that it's easily rolled back if not what you mean, @MeaganLP.
