### ISSUE TITLE
Text Size

### ISSUE THREAD

**Issue by AmoryH** [CityOfPhiladelphia/community-health-explorer#45]
The description text is much larger than the note and source text for Planning District, Citywide Over Time, and Top 10. All text should be the same size. Maybe make all text the larger size so it's easier to read.

**Comment by laurenancona** [comment]
This is an intentional design decision; the two fields `note` and `source` are intended to be clarifying/annotation-style content, whereas `description` is body content.

**Comment by MeaganLP** [comment]
I agree with Lauren about leaving the Description text larger than the rest.

**Comment by Kistine** [comment]
I'm a fan too of the styling - makes it easier to quickly understand that they're notations - otherwise, I think thinks like '5 year estimate' might feel unfinished and out of place.

**Comment by MeaganLP** [comment]
However, if we could make the racial disparity tab match the others that would be good. Right now Description is not larger on that page.

**Comment by AmoryH** [comment]
Okay, I can get on board with that.

**Comment by laurenancona** [comment]
@MeaganLP That's a bug; will fix.

**Comment by laurenancona** [comment]
Description is correctly displaying larger for me, closing for now.

**Comment by AmoryH** [comment]
Still not displaying larger on our end for racial disparity.

**Comment by laurenancona** [comment]
- [x] Check webkit font sizes

**Comment by laurenancona** [comment]
Fixed in https://github.com/CityOfPhiladelphia/community-health-explorer/commit/1bd068ba55d47e889c067e456db79602b37a46ac
