### ISSUE TITLE
Back to top text

### ISSUE THREAD

**Issue by AmoryH** [CityOfPhiladelphia/community-health-explorer#46]
Planning Districts and Top 10 only have the up arrow - add "back to top" text next to it so matches the other pages.

**Comment by laurenancona** [comment]
Ah! are you by chance on a mobile device, @AmoryH? This is an in-progress update to hide the text on mobile devices only. I hadn't pushed the change for the last 2 pages.

**Comment by AmoryH** [comment]
Ha, nope I was on my desktop @laurenancona

**Comment by karissademi** [comment]
#52 Will fix this.

**Comment by karissademi** [comment]
#52 was merged.
