### ISSUE TITLE
Planning District Dimension Problems

### ISSUE THREAD

**Issue by MeaganLP** [CityOfPhiladelphia/community-health-explorer#48]
- Not all data is appearing in the application. The one I noticed is second hand smoke at home among children
- Unemployment and children in single parent homes in social determinants does not fit in its box; so I wonder where else this could be happening or happen in the future

**Comment by Kistine** [comment]
I see the first issue too.

However, I'm not having the same issue with 'unemployment' et. al. cards - they all look contained to me ::perplexed::

**Comment by laurenancona** [comment]
@MeaganLP can you give an example of which planning districts?

**Comment by MeaganLP** [comment]
@laurenancona So it seems fine now that I'm back on my desktop computer whose screen is ginormous. I noticed it when working from a laptop this morning

**Comment by laurenancona** [comment]
The cards are only hidden when districts don't have data for that dimension/metric combination.
Not a bug, feature :)
