### ISSUE TITLE
Citywide over time charts show abbreviated years

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/community-health-explorer#5]
It looks like the [citywide over time](http://cityofphiladelphia.github.io/community-health-explorer/citywide-over-time/) charts are showing years as `03`, `04`, `05`, etc. rather than `2003`, `2004`.

**Comment by laurenancona** [comment]
Need to add media query per Chartist docs: http://gionkunz.github.io/chartist-js/examples.html#example-bar-extreme-responsive
