### ISSUE TITLE
Sections cut off using drop down menu jump - Planning Districts

### ISSUE THREAD

**Issue by AmoryH** [CityOfPhiladelphia/community-health-explorer#55]
When you use the drop down menu on the planning districts page to jump to a category, that section is a little cut off. I think it's because the drop down menus are placed on a different part of the page than the other dimensions so it's cutting the top part of each section off.

**Comment by laurenancona** [comment]
@karissademi I think this is a trade-off after making the bottom padding thing work. Do you know how we could offset those anchors?

**Comment by karissademi** [comment]
I have a solution in mind.
